
require "mfallon.plugins"
require "mfallon.options"
require "mfallon.keymaps"
require "mfallon.colorschemes"
require "mfallon.nvimtree"
require "mfallon.fzf"
require "mfallon.treesitter"
require "mfallon.highlights"
require "mfallon.mason"
require "mfallon.lspconfig"
require "mfallon.gitsigns"
require "mfallon.autocommands"
require "mfallon.lualine"
